const std = @import("std");
const root = @import("root.zig");
const c = @import("cgrpc");
const client = @import("client.zig");

const Allocator = std.mem.Allocator;
const Channel = root.Channel;
const Deadline = root.Deadline;
const PluckQueue = root.PluckQueue;

/// Returns the type of the request parameter of a VTable method.
fn requestOf(comptime VTable: type, comptime method: []const u8) type {
    for (@typeInfo(VTable).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, method)) {
            const fn_type = @typeInfo(f.type).pointer.child;
            return @typeInfo(fn_type).@"fn".params[1].type.?;
        }
    }
    @compileError("method '" ++ method ++ "' not found in service");
}

/// Returns the response type (payload of the error union) of a VTable method.
fn responseOf(comptime VTable: type, comptime method: []const u8) type {
    for (@typeInfo(VTable).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, method)) {
            const fn_type = @typeInfo(f.type).pointer.child;
            const return_type = @typeInfo(fn_type).@"fn".return_type.?;
            return @typeInfo(return_type).error_union.payload;
        }
    }
    @compileError("method '" ++ method ++ "' not found in service");
}

/// Typed gRPC client stub for a protobuf-generated service.
///
/// `ServiceFn` is a function of the form `fn(comptime UserDataType: type, comptime ErrorSet: type) type`
/// as generated by protoc-gen-zig (zig-protobuf PR #149).
///
/// Example:
/// ```zig
/// var stub: grpc.Stub(protocol.Greeter) = .{
///     .channel = &channel,
///     .queue = &queue,
///     .allocator = gpa,
/// };
/// var reply = try stub.call("SayHello", request, deadline);
/// defer reply.deinit(gpa);
/// ```
pub fn Stub(comptime ServiceFn: anytype) type {
    // Instantiate the VTable with dummy types just to inspect structure.
    const VTable = ServiceFn(struct {}, error{});

    return struct {
        channel: *Channel,
        queue: *PluckQueue,
        allocator: Allocator,

        pub const Error = error{
            Timeout,
            GrpcError,
            NoResponse,
            QueueShutdown,
        };

        pub const Metadata = struct {
            key: []const u8,
            value: []const u8,
        };

        pub const CallOptions = struct {
            metadata: []const Metadata = &.{},
        };

        /// Perform a unary RPC call.
        ///
        /// The returned value is allocated using `self.allocator` and must be freed by the caller.
        pub fn call(
            self: *@This(),
            comptime method: []const u8,
            request: requestOf(VTable, method),
            deadline: Deadline,
            options: CallOptions,
        ) (Error || error{OutOfMemory} || anyerror)!responseOf(VTable, method) {
            const path = "/" ++ VTable.package ++ "." ++ VTable.service_name ++ "/" ++ method;

            var arena = std.heap.ArenaAllocator.init(self.allocator);
            defer arena.deinit();
            const arena_alloc = arena.allocator();

            var encoded: std.Io.Writer.Allocating = .init(arena_alloc);
            defer encoded.deinit();
            try request.encode(&encoded.writer, arena_alloc);

            const grpc_call = self.channel.createCall(self.queue, path, deadline);
            defer c.grpc_call_unref(grpc_call);

            var batch: client.Batch = .init(arena_alloc);
            defer batch.deinit();
            for (options.metadata) |m| try batch.addMetadata(m.key, m.value);
            try batch.setMessageToSend(encoded.written());
            batch.expectReceivedMessage();
            try batch.start(grpc_call);

            return switch (try batch.wait(self.queue, deadline)) {
                .timeout => Error.Timeout,
                .failure => Error.GrpcError,
                .success => |bytes| {
                    const b = bytes orelse return Error.NoResponse;
                    var reader: std.Io.Reader = .fixed(b);
                    return responseOf(VTable, method).decode(&reader, self.allocator);
                },
            };
        }
    };
}
