const std = @import("std");
const root = @import("root.zig");
const c = @import("cgrpc");
const client = @import("client.zig");

const Allocator = std.mem.Allocator;
const Channel = root.Channel;
const Deadline = root.Deadline;
const PluckQueue = root.PluckQueue;

/// Returns the error set of a type's encode method.
fn encodeError(comptime Request: type) type {
    return @typeInfo(@typeInfo(@TypeOf(Request.encode)).@"fn".return_type.?).error_union.error_set;
}

/// Returns the error set of a type's decode method.
fn decodeError(comptime Response: type) type {
    return @typeInfo(@typeInfo(@TypeOf(Response.decode)).@"fn".return_type.?).error_union.error_set;
}

/// Returns the type of the request parameter of a VTable method.
fn requestOf(comptime VTable: type, comptime method: []const u8) type {
    for (@typeInfo(VTable).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, method)) {
            const fn_type = @typeInfo(f.type).pointer.child;
            return @typeInfo(fn_type).@"fn".params[1].type.?;
        }
    }
    @compileError("method '" ++ method ++ "' not found in service");
}

/// Returns the response type (payload of the error union) of a VTable method.
fn responseOf(comptime VTable: type, comptime method: []const u8) type {
    for (@typeInfo(VTable).@"struct".fields) |f| {
        if (std.mem.eql(u8, f.name, method)) {
            const fn_type = @typeInfo(f.type).pointer.child;
            const return_type = @typeInfo(fn_type).@"fn".return_type.?;
            return @typeInfo(return_type).error_union.payload;
        }
    }
    @compileError("method '" ++ method ++ "' not found in service");
}

/// Typed gRPC client stub for a protobuf-generated service.
///
/// `ServiceFn` is a function of the form `fn(comptime UserDataType: type, comptime ErrorSet: type) type`
/// as generated by protoc-gen-zig (zig-protobuf PR #149).
///
/// Example:
/// ```zig
/// var stub: grpc.Stub(protocol.Greeter) = .{
///     .channel = &channel,
///     .queue = &queue,
///     .allocator = gpa,
/// };
/// var reply = try stub.call(.SayHello, request, .{ .deadline = .{ .duration = .fromSeconds(2) } });
/// defer reply.deinit(gpa);
/// ```
pub fn Stub(comptime ServiceFn: anytype) type {
    // Instantiate the VTable with dummy types just to inspect structure.
    const VTable = ServiceFn(struct {}, error{});

    return struct {
        channel: *Channel,
        queue: *PluckQueue,
        allocator: Allocator,

        /// Enum of available RPC methods, derived from the service definition.
        pub const Method = std.meta.FieldEnum(VTable);

        /// High-level gRPC call outcomes.
        pub const Error = error{
            /// No response received before the deadline expired.
            Timeout,
            /// The server returned a non-OK status.
            GrpcError,
            /// The call succeeded but no response message was present.
            NoResponse,
            /// The completion queue was shut down before the call completed.
            QueueShutdown,
        };

        /// Full error set for call(), including transport, encoding and decoding errors.
        pub fn CallError(comptime method: Method) type {
            const Request = requestOf(VTable, @tagName(method));
            const Response = responseOf(VTable, @tagName(method));
            return Error || client.Batch.Error || client.Batch.WaitError || encodeError(Request) || decodeError(Response);
        }

        pub const Metadata = struct {
            key: []const u8,
            value: []const u8,
        };

        pub const CallOptions = struct {
            deadline: Deadline,
            metadata: []const Metadata = &.{},
        };

        /// Perform a unary RPC call.
        ///
        /// The returned value is allocated using `self.allocator` and must be freed by the caller.
        pub fn call(
            self: *@This(),
            comptime method: Method,
            request: requestOf(VTable, @tagName(method)),
            options: CallOptions,
        ) CallError(method)!responseOf(VTable, @tagName(method)) {
            const method_name = @tagName(method);
            const path = "/" ++ VTable.package ++ "." ++ VTable.service_name ++ "/" ++ method_name;

            var arena = std.heap.ArenaAllocator.init(self.allocator);
            defer arena.deinit();
            const arena_alloc = arena.allocator();

            var encoded: std.Io.Writer.Allocating = .init(arena_alloc);
            defer encoded.deinit();
            try request.encode(&encoded.writer, arena_alloc);

            const grpc_call = self.channel.createCall(self.queue, path, options.deadline);
            defer c.grpc_call_unref(grpc_call);

            var batch: client.Batch = .init(arena_alloc);
            defer batch.deinit();
            for (options.metadata) |m| try batch.addMetadata(m.key, m.value);
            try batch.setMessageToSend(encoded.written());
            batch.expectReceivedMessage();
            try batch.start(grpc_call);

            return switch (try batch.wait(self.queue, options.deadline)) {
                .timeout => Error.Timeout,
                .failure => |f| {
                    std.log.err("gRPC error {d}: {s}", .{ f.code, f.details });
                    return Error.GrpcError;
                },
                .success => |bytes| {
                    const b = bytes orelse return Error.NoResponse;
                    var reader: std.Io.Reader = .fixed(b);
                    return responseOf(VTable, method_name).decode(&reader, self.allocator);
                },
            };
        }
    };
}
